DROP TABLE IF EXISTS leaderboard;

CREATE TABLE leaderboard (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL,
   score INTEGER NOT NULL,
   phone_num INTEGER,
   time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
